[project]
name = "tg-translator"
version = "0.1.0"
description = "Telegram channel message translator"
dependencies = [
    "python-telegram-bot",
    "telethon",
    "anthropic",
]

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"
